In [1]:
import numpy as np
%run ../gaussj.py

In [2]:
a = np.random.random(size=(4,4))
b = np.random.random(size=(4,3))

In [3]:
a

array([[0.09803429, 0.00470105, 0.16598382, 0.16288186],
       [0.46033607, 0.90335624, 0.60684602, 0.73645238],
       [0.48343806, 0.9286728 , 0.89489366, 0.28394927],
       [0.12076117, 0.32894532, 0.81764059, 0.42126352]])

In [4]:
b

array([[0.30355319, 0.36957788, 0.34641876],
       [0.6779521 , 0.54794141, 0.47397917],
       [0.8174115 , 0.16598033, 0.00646055],
       [0.05287819, 0.81654833, 0.60811149]])

In [5]:
np.linalg.inv(a)

array([[ 8.67812274, -0.80045833,  1.87528679, -3.22006434],
       [-5.20383871,  0.97508291,  0.06010159,  0.2669184 ],
       [ 0.55240728, -1.06908363,  0.59217254,  1.25623292],
       [ 0.5035507 ,  1.54307568, -1.73387022,  0.65021095]])

In [6]:
np.linalg.solve(a,b)

array([[ 3.45420927,  0.45056048,  0.68082115],
       [-0.85534045, -1.1610079 , -1.17783391],
       [-0.00662653,  0.74242619,  0.45239631],
       [-0.18391765,  1.27475658,  1.29002414]])

In [7]:
gaussj(a,4,b,3)

In [8]:
a

array([[ 8.67812274, -0.80045833,  1.87528679, -3.22006434],
       [-5.20383871,  0.97508291,  0.06010159,  0.2669184 ],
       [ 0.55240728, -1.06908363,  0.59217254,  1.25623292],
       [ 0.5035507 ,  1.54307568, -1.73387022,  0.65021095]])

In [9]:
b

array([[ 3.45420927,  0.45056048,  0.68082115],
       [-0.85534045, -1.1610079 , -1.17783391],
       [-0.00662653,  0.74242619,  0.45239631],
       [-0.18391765,  1.27475658,  1.29002414]])